/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package crud;

import javax.swing.JOptionPane;

/**
 *
 * @author MSI GF63
 */
public class Menu extends javax.swing.JFrame {

    Login bb = new Login();

    /** Creates new form Menu */
    public Menu() {
        if (Session.getStatusLogin() == "AKTIF") {
            initComponents();
            setSessionNama();
        } else {
            dispose();
            LoginForm form = new LoginForm();
            form.setVisible(true);
        }
    }

    private void setSessionNama() {
        label_nama.setText("Hai " + Session.getNama());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nama = new javax.swing.JLabel();
        label_keterangan = new javax.swing.JLabel();
        jMenuAplikasiBar = new javax.swing.JMenuBar();
        jMenuAplikasi = new javax.swing.JMenu();
        jMenuKeluar = new javax.swing.JMenuItem();
        jMenuCRUD = new javax.swing.JMenu();
        jMenuCRUDSiswa = new javax.swing.JMenuItem();
        jMenuPolimorfisme = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_nama.setText("Hai Nama User");

        label_keterangan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_keterangan.setText("Selamat datang di Aplikasi Praktikum PBO");

        jMenuAplikasiBar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuAplikasi.setText("Aplikasi");
        jMenuAplikasi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuKeluar.setText("Keluar");
        jMenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKeluarActionPerformed(evt);
            }
        });
        jMenuAplikasi.add(jMenuKeluar);

        jMenuAplikasiBar.add(jMenuAplikasi);

        jMenuCRUD.setText("CRUD");
        jMenuCRUD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuCRUDSiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuCRUDSiswa.setText("CRUD Siswa");
        jMenuCRUDSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCRUDSiswaActionPerformed(evt);
            }
        });
        jMenuCRUD.add(jMenuCRUDSiswa);

        jMenuAplikasiBar.add(jMenuCRUD);

        jMenuPolimorfisme.setText("Polimorfisme");
        jMenuPolimorfisme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuAplikasiBar.add(jMenuPolimorfisme);

        setJMenuBar(jMenuAplikasiBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(label_nama)
                    .add(label_keterangan))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(50, 50, 50)
                .add(label_nama)
                .add(18, 18, 18)
                .add(label_keterangan)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKeluarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar?", "Warning", 2) == JOptionPane.YES_OPTION) {
            bb.Logout(Session.getUserID());
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuKeluarActionPerformed

    private void jMenuCRUDSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCRUDSiswaActionPerformed
        // TODO add your handling code here:
        try {
            Form_Siswa form = new Form_Siswa();
            form.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jMenuCRUDSiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAplikasi;
    private javax.swing.JMenuBar jMenuAplikasiBar;
    private javax.swing.JMenu jMenuCRUD;
    private javax.swing.JMenuItem jMenuCRUDSiswa;
    private javax.swing.JMenuItem jMenuKeluar;
    private javax.swing.JMenu jMenuPolimorfisme;
    private javax.swing.JLabel label_keterangan;
    private javax.swing.JLabel label_nama;
    // End of variables declaration//GEN-END:variables

}
